# **MINI HACKATHON**

# **PREPROCESSING**

**Import**

In [2]:
import pandas as pd
import numpy as np

**Masukkan data**

**Data Train**

In [3]:
train = pd.read_csv("Train.csv")
train

ID  Provinsi  KodeKabKot  Y  X1  ...  X6     Z1      Z2      Z3       Z4
0          1        11        1101  0   1  ...   1  1.077  15.075  26.919  390.869
1          2        11        1101  0   1  ...   0  1.077  15.075  26.919  390.869
2          4        11        1101  0   0  ...   1  1.077  15.075  26.919  390.869
3          7        11        1101  0   0  ...   1  1.077  15.075  26.919  390.869
4          8        11        1101  0   1  ...   0  1.077  15.075  26.919  390.869
...      ...       ...         ... ..  ..  ...  ..    ...     ...     ...      ...
13621  19524        94        9471  1   0  ...   1  1.757   3.262  48.936  209.045
13622  19526        94        9471  0   1  ...   1  1.757   3.262  48.936  209.045
13623  19527        94        9471  0   0  ...   1  1.757   3.262  48.936  209.045
13624  19529        94        9471  0   0  ...   1  1.757   3.262  48.936  209.045
13625  19530        94        9471  1   0  ...   1  1.757   3.262  48.936  209.045

[13626 rows x 14 columns]

**Data Test**

In [4]:
test = pd.read_csv("Test.csv")
test

ID  Provinsi  KodeKabKot  X1  X2  ...  X6     Z1      Z2      Z3       Z4
0         3        11        1101   1  39  ...   1  1.077  15.075  26.919  390.869
1         5        11        1101   0  32  ...   1  1.077  15.075  26.919  390.869
2         6        11        1101   1  32  ...   1  1.077  15.075  26.919  390.869
3        10        11        1101   1  28  ...   0  1.077  15.075  26.919  390.869
4        17        11        1101   0  31  ...   1  1.077  15.075  26.919  390.869
...     ...       ...         ...  ..  ..  ...  ..    ...     ...     ...      ...
5901  19515        94        9471   1  39  ...   1  1.757   3.262  48.936  209.045
5902  19525        94        9471   0  30  ...   1  1.757   3.262  48.936  209.045
5903  19528        94        9471   0  22  ...   1  1.757   3.262  48.936  209.045
5904  19531        94        9471   0  40  ...   1  1.757   3.262  48.936  209.045
5905  19532        94        9471   0  38  ...   1  1.757   3.262  48.936  209.045

[5906 rows x 13 columns]

**Menggunakan Data Train**

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13626 entries, 0 to 13625
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   ID          13626 non-null  int64  
 1   Provinsi    13626 non-null  int64  
 2   KodeKabKot  13626 non-null  int64  
 3   Y           13626 non-null  int64  
 4   X1          13626 non-null  int64  
 5   X2          13626 non-null  int64  
 6   X3          13626 non-null  int64  
 7   X4          13626 non-null  int64  
 8   X5          13626 non-null  int64  
 9   X6          13626 non-null  int64  
 10  Z1          13626 non-null  float64
 11  Z2          13626 non-null  float64
 12  Z3          13626 non-null  float64
 13  Z4          13621 non-null  float64
dtypes: float64(4), int64(10)
memory usage: 1.5 MB


In [6]:
train.isnull().sum()

ID            0
Provinsi      0
KodeKabKot    0
Y             0
X1            0
X2            0
X3            0
X4            0
X5            0
X6            0
Z1            0
Z2            0
Z3            0
Z4            5
dtype: int64

In [7]:
trainDrop = train.dropna(axis=0)
trainDrop.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13621 entries, 0 to 13625
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   ID          13621 non-null  int64  
 1   Provinsi    13621 non-null  int64  
 2   KodeKabKot  13621 non-null  int64  
 3   Y           13621 non-null  int64  
 4   X1          13621 non-null  int64  
 5   X2          13621 non-null  int64  
 6   X3          13621 non-null  int64  
 7   X4          13621 non-null  int64  
 8   X5          13621 non-null  int64  
 9   X6          13621 non-null  int64  
 10  Z1          13621 non-null  float64
 11  Z2          13621 non-null  float64
 12  Z3          13621 non-null  float64
 13  Z4          13621 non-null  float64
dtypes: float64(4), int64(10)
memory usage: 1.6 MB


In [8]:
trainDrop.isnull().sum()


ID            0
Provinsi      0
KodeKabKot    0
Y             0
X1            0
X2            0
X3            0
X4            0
X5            0
X6            0
Z1            0
Z2            0
Z3            0
Z4            0
dtype: int64

**Masukkan Data Test**

In [9]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5906 entries, 0 to 5905
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   ID          5906 non-null   int64  
 1   Provinsi    5906 non-null   int64  
 2   KodeKabKot  5906 non-null   int64  
 3   X1          5906 non-null   int64  
 4   X2          5906 non-null   int64  
 5   X3          5906 non-null   int64  
 6   X4          5906 non-null   int64  
 7   X5          5906 non-null   int64  
 8   X6          5906 non-null   int64  
 9   Z1          5906 non-null   float64
 10  Z2          5906 non-null   float64
 11  Z3          5906 non-null   float64
 12  Z4          5901 non-null   float64
dtypes: float64(4), int64(9)
memory usage: 600.0 KB


In [10]:
test.isnull().sum()

ID            0
Provinsi      0
KodeKabKot    0
X1            0
X2            0
X3            0
X4            0
X5            0
X6            0
Z1            0
Z2            0
Z3            0
Z4            5
dtype: int64

In [11]:
# Langkah 1
rataan = test['Z4'].median()
# Langkah 2
test['Z4'] = test['Z4'].fillna(rataan)
# Langkah 3
test['Z4'].isna().sum()

0

In [12]:
rataan = test['Z4'].median()
rataan

159.925

In [13]:
tes = test.drop( ['ID','Provinsi'],axis=1) 
tes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5906 entries, 0 to 5905
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   KodeKabKot  5906 non-null   int64  
 1   X1          5906 non-null   int64  
 2   X2          5906 non-null   int64  
 3   X3          5906 non-null   int64  
 4   X4          5906 non-null   int64  
 5   X5          5906 non-null   int64  
 6   X6          5906 non-null   int64  
 7   Z1          5906 non-null   float64
 8   Z2          5906 non-null   float64
 9   Z3          5906 non-null   float64
 10  Z4          5906 non-null   float64
dtypes: float64(4), int64(7)
memory usage: 507.7 KB


**Membuat Model**

**membagi data train menjadi hitung (X) dan target (Y)**

In [14]:
varX = trainDrop.drop(['Y', 'ID', 'Provinsi'],axis=1) 
varX.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13621 entries, 0 to 13625
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   KodeKabKot  13621 non-null  int64  
 1   X1          13621 non-null  int64  
 2   X2          13621 non-null  int64  
 3   X3          13621 non-null  int64  
 4   X4          13621 non-null  int64  
 5   X5          13621 non-null  int64  
 6   X6          13621 non-null  int64  
 7   Z1          13621 non-null  float64
 8   Z2          13621 non-null  float64
 9   Z3          13621 non-null  float64
 10  Z4          13621 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 1.2 MB


In [15]:
varY = trainDrop['Y']
varY.head()

0    0
1    0
2    0
3    0
4    0
Name: Y, dtype: int64

**Split data**

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(varX, varY, test_size=0.01, random_state=0)

**Featured Scalling**

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
tes = sc.transform(tes)

**Import Library Analisis**

In [18]:
from sklearn.metrics import classification_report,accuracy_score
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay
# Import untuk Grid
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

# **XGBOOST**


In [19]:
from xgboost import XGBClassifier
xgboost = XGBClassifier(random_state = 0)
xgboost.fit(X_train, y_train)

XGBClassifier()

In [20]:
y_predXGB = xgboost.predict(X_test)
y_predXGB

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0])

In [21]:
print(classification_report(y_test, y_predXGB))


              precision    recall  f1-score   support

           0       0.76      0.74      0.75        92
           1       0.49      0.51      0.50        45

    accuracy                           0.66       137
   macro avg       0.62      0.63      0.62       137
weighted avg       0.67      0.66      0.67       137



In [22]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_predXGB), ": is the confusion matrix")

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_predXGB), ": is the accuracy score")

from sklearn.metrics import precision_score
print(precision_score(y_test, y_predXGB, average='weighted'), ": is the precision score")

from sklearn.metrics import recall_score
print(recall_score(y_test, y_predXGB, average='weighted'), ": is the recall score")

from sklearn.metrics import f1_score
print(f1_score(y_test, y_predXGB, average='weighted'), ": is the f1 score")

[[68 24]
 [22 23]] : is the confusion matrix
0.6642335766423357 : is the accuracy score
0.6681196182982174 : is the precision score
0.6642335766423357 : is the recall score
0.666038341220823 : is the f1 score


**Buat Submission XGBOOST**


In [23]:
Y = xgboost.predict(tes)
print(Y)

[0 0 0 ... 0 0 0]


In [24]:
ID = test['ID']
ID.head()

0     3
1     5
2     6
3    10
4    17
Name: ID, dtype: int64

In [25]:
Sub = {'ID': ID,
        'Y': Y
        }

df = pd.DataFrame(Sub, columns= ['ID', 'Y'])

df.to_csv ('XGBoost.csv', index = False, header=True)

print (df)

         ID  Y
0         3  0
1         5  0
2         6  0
3        10  0
4        17  0
...     ... ..
5901  19515  0
5902  19525  0
5903  19528  0
5904  19531  0
5905  19532  0

[5906 rows x 2 columns]


# **ADABOOST**

In [26]:
from sklearn.ensemble import AdaBoostClassifier
adaB = AdaBoostClassifier(random_state=0)
adaB.fit(X_train, y_train)

AdaBoostClassifier(random_state=0)

In [27]:
y_predABC = adaB.predict(X_test)
y_predABC

array([1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0])

In [28]:
print(classification_report(y_test, y_predABC))

              precision    recall  f1-score   support

           0       0.78      0.75      0.76        92
           1       0.52      0.56      0.54        45

    accuracy                           0.69       137
   macro avg       0.65      0.65      0.65       137
weighted avg       0.69      0.69      0.69       137



In [29]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_predABC), ": is the confusion matrix")

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_predABC), ": is the accuracy score")

from sklearn.metrics import precision_score
print(precision_score(y_test, y_predABC, average='weighted'), ": is the precision score")

from sklearn.metrics import recall_score
print(recall_score(y_test, y_predABC, average='weighted'), ": is the recall score")

from sklearn.metrics import f1_score
print(f1_score(y_test, y_predABC, average='weighted'), ": is the f1 score")

[[69 23]
 [20 25]] : is the confusion matrix
0.6861313868613139 : is the accuracy score
0.691703231362257 : is the precision score
0.6861313868613139 : is the recall score
0.6885926627440625 : is the f1 score


**Buat Submission ADABOOST**

In [30]:
YY = adaB.predict(tes)
print(YY)

[0 0 0 ... 0 0 0]


In [31]:
ID = test['ID']
ID.head()

0     3
1     5
2     6
3    10
4    17
Name: ID, dtype: int64

In [32]:
Sub = {'ID': ID,
        'Y': YY
        }

df = pd.DataFrame(Sub, columns= ['ID', 'Y'])

df.to_csv ('Adaboost.csv', index = False, header=True)

print (df)

         ID  Y
0         3  0
1         5  0
2         6  0
3        10  0
4        17  0
...     ... ..
5901  19515  0
5902  19525  0
5903  19528  0
5904  19531  0
5905  19532  0

[5906 rows x 2 columns]


# **RANDOM FOREST**

In [33]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [34]:
y_predrf = rf.predict(X_test)
y_predrf

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0])

In [35]:
print(classification_report(y_test, y_predrf))

              precision    recall  f1-score   support

           0       0.75      0.72      0.73        92
           1       0.47      0.51      0.49        45

    accuracy                           0.65       137
   macro avg       0.61      0.61      0.61       137
weighted avg       0.66      0.65      0.65       137



In [36]:
print(confusion_matrix(y_test, y_predrf), ": is the confusion matrix")

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_predrf), ": is the accuracy score")

from sklearn.metrics import precision_score
print(precision_score(y_test, y_predrf, average='weighted'), ": is the precision score")

from sklearn.metrics import recall_score
print(recall_score(y_test, y_predrf, average='weighted'), ": is the recall score")

from sklearn.metrics import f1_score
print(f1_score(y_test, y_predrf, average='weighted'), ": is the f1 score")

[[66 26]
 [22 23]] : is the confusion matrix
0.6496350364963503 : is the accuracy score
0.6578280947415462 : is the precision score
0.6496350364963503 : is the recall score
0.6531966661489879 : is the f1 score


**Buat submission RANDOM FOREST**

In [37]:
YRF = rf.predict(tes)
print(YRF)

[0 0 0 ... 0 1 0]


In [38]:
ID = test['ID']
ID.head()

0     3
1     5
2     6
3    10
4    17
Name: ID, dtype: int64

In [39]:
Sub = {'ID': ID,
        'Y': YRF
        }

df = pd.DataFrame(Sub, columns= ['ID', 'Y'])

df.to_csv ('RandomF.csv', index = False, header=True)

print (df)

         ID  Y
0         3  0
1         5  0
2         6  0
3        10  1
4        17  0
...     ... ..
5901  19515  0
5902  19525  1
5903  19528  0
5904  19531  1
5905  19532  0

[5906 rows x 2 columns]


# **DECISION TREE**

In [40]:
from sklearn.tree import DecisionTreeClassifier
clf_entropy = DecisionTreeClassifier()
clf_entropy.fit(X_train, y_train)
clf_entropy.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': None,
 'splitter': 'best'}

In [41]:
y_predDT = clf_entropy.predict(X_test)
accuracy = accuracy_score(y_test, y_predDT)
print("Accuracy :",accuracy)

Accuracy : 0.6204379562043796


# **NAIVE BAYES**

In [42]:
from sklearn.naive_bayes import GaussianNB
modelnb = GaussianNB()
modelnb.fit(X_train, y_train)

GaussianNB()

In [43]:
y_predNB = modelnb.predict(X_test)
y_predNB

array([1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0])

In [44]:
print(classification_report(y_test, y_predNB))

              precision    recall  f1-score   support

           0       0.75      0.52      0.62        92
           1       0.40      0.64      0.49        45

    accuracy                           0.56       137
   macro avg       0.57      0.58      0.55       137
weighted avg       0.63      0.56      0.57       137



# **KNN**

In [45]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=10, p=2, metric='euclidean')
clf.fit(X_train, y_train)
clf.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'euclidean',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 10,
 'p': 2,
 'weights': 'uniform'}

In [46]:
y_predKNN = clf.predict(X_test)
y_predKNN

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0])

In [47]:
print(classification_report(y_test, y_predKNN))

              precision    recall  f1-score   support

           0       0.74      0.80      0.77        92
           1       0.51      0.42      0.46        45

    accuracy                           0.68       137
   macro avg       0.63      0.61      0.62       137
weighted avg       0.67      0.68      0.67       137



**SUBMISSION**

In [48]:
YKNN = clf.predict(tes)
print(YKNN)

[0 0 0 ... 0 1 1]


In [49]:
ID = test['ID']
ID.head()

0     3
1     5
2     6
3    10
4    17
Name: ID, dtype: int64

In [50]:
Sub = {'ID': ID,
        'Y': YKNN
        }

df = pd.DataFrame(Sub, columns= ['ID', 'Y'])

df.to_csv ('KNN1.csv', index = False, header=True)

print (df)

         ID  Y
0         3  0
1         5  0
2         6  0
3        10  0
4        17  0
...     ... ..
5901  19515  1
5902  19525  1
5903  19528  0
5904  19531  1
5905  19532  1

[5906 rows x 2 columns]


# **TRY (buat coba-coba)**


In [51]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

# acc = dtc.score(X_test, y_test)*100
# accuracies['Decision Tree'] = acc
# print("Decision Tree Test Accuracy {:.2f}%".format(acc))

DecisionTreeClassifier()

In [52]:
y_predDTC = dtc.predict(X_test)
y_predDTC
print(classification_report(y_test, y_predDTC))

              precision    recall  f1-score   support

           0       0.76      0.62      0.68        92
           1       0.44      0.60      0.50        45

    accuracy                           0.61       137
   macro avg       0.60      0.61      0.59       137
weighted avg       0.65      0.61      0.62       137

